# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.IntegerField(choices=[(1, b'Author'), (2, b'EDITOR'), (3, b'REVIEWER')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_pc_formset2.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_pc_formset2.Person'),
        ),
    ]
